name: languages-ratio
on:
  schedule:
    - cron: "0 15,3 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          $jsonName = 'languages-ratio.json'
          $languageByteMap = @{}
          $sumByte = ,0
          $headers = @{'authorization' = 'Bearer ${{ secrets.GITHUB_TOKEN }}'}
          (Invoke-RestMethod -Uri https://api.github.com/users/shikatan0/repos -Headers $headers)
          | & {
            process {
              $resultObject = Invoke-RestMethod -Uri $_.languages_url -Headers $headers
              $propertyNames = $resultObject.psobject.properties.name
              if ($null -eq $propertyNames) {
                return
              }
              $propertyNames | & {
                process {
                  $sumByte[0] += $resultObject.$_
                  if ($languageByteMap.ContainsKey($_)) {
                    $languageByteMap.$_ += $resultObject.$_
                  }
                  else {
                    $languageByteMap.$_ = $resultObject.$_
                  }
                }
              }
            }
          }
          $languageRatioMap = [ordered]@{}
          $languageByteMap.GetEnumerator() | Sort-Object -Property value -Descending | % {$languageRatioMap[$_.Key] = $_.value / $sumByte[0] * 100}
          $currentJson = $languageRatioMap | ConvertTo-JSON
          if (Test-Path $jsonName) {
            $beforeJson = Get-Content -Path $jsonName -Raw
            if ($currentJson -ne $beforeJson) {
              $currentJson | Out-File $jsonName
              git config --global user.name ${{ github.actor }}
              git config --global user.email ${{ github.actor }}@users.noreply.github.com
              git add languages-ratio.json
              git commit -m u
              git push origin master
            }
          }
          else {
            $currentJson | Out-File $jsonName
            git config --global user.name ${{ github.actor }}
            git config --global user.email ${{ github.actor }}@users.noreply.github.com
            git add languages-ratio.json
            git commit -m u
            git push origin master
          }
        shell: pwsh
