name: languages-ratio
on:
  schedule:
    - cron: "0 15,3 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: pwsh
        run: ./main.ps1 ${{ secrets.REPO_ACCESS_TOKEN }} ${{ github.actor }}
